### ISSUE TITLE
Skip sentence splitting

### ISSUE THREAD

**Issue by mdtux89** [dhfbk/tint#1]
Hi, is it possible to skip the sentence splitting step? For example, in CoreNLP you can specify the option "ssplit.eolonly: true".

Thanks,
Marco

**Comment by ziorufus** [comment]
Dear Marco,
thank you for your message. I've updated the 1.0-SNAPSHOT version of tint with the features you requested (that were already in the TODO list). You can add the following settings to the `ita_toksent` module:

* `newlineIsSentenceBreak` always breaks sentence on newline (default `true`)
* `tokenizeOnlyOnSpace` tokenises on white spaces instead of applying the tokenizer (default `false`)
* `ssplitOnlyOnNewLine` means that only newlines are considered as sentence breaks (default `false`)

In the [`TintTest`](https://github.com/dhfbk/tint/blob/develop/tint-runner/src/test/java/TintTest.java) class you can find an example on how to include the pipeline in a Java project and how to set a custom setting.

Let me know if you have other problems.
Best,
Alessio

**Comment by mdtux89** [comment]
Grazie :)
